### PR TITLE
Update motion_sensor.py

### PR DESCRIPTION
**Pull request by st-amusic**

### CODE REVIEW

**Comment by ChadiEM** [comment]
@st-amusic Thanks for your contribution!

What value were you getting other than 0, 1, or 2? Do you think it's worth adding to the enum instead of catching a ValueError here?

**Comment by st-amusic** [comment]
hello, it was 3. I thought try except would prevent crash for unknown or futur states.

Traceback (most recent call last):
  File "philips_hue_hooks/hue_hooks.py", line 81, in <module>
    poller.run()
  File "/opt/lc/philips_hue_hooks/poller.py", line 34, in run
    self.send_updates(json, 'sensor', sensor_id)
  File "/opt/lc/philips_hue_hooks/poller.py", line 50, in send_updates
    updated_state = current_device.update(device_json)
  File "/opt/lc/philips_hue_hooks/sensors/motion_sensor.py", line 14, in update
    new_state = State(state_from_json)
  File "/usr/local/lib/python3.8/enum.py", line 309, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.8/enum.py", line 600, in __new__
    raise exc
  File "/usr/local/lib/python3.8/enum.py", line 584, in __new__
    result = cls._missing_(value)
  File "/usr/local/lib/python3.8/enum.py", line 613, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 3 is not a valid State

**Comment by ChadiEM** [comment]
You're right. Two things here:
- Any unknown value should not fail the application
- The value here in particular should be handled

I thought about it, and I have made changes where I publish the raw body as obtained from the hub without any further processing. This should fix both issues above, and yet make it compatible with any light or sensor. It would then be up to the user to do the post-processing.

Let me know what you think.

**Comment by st-amusic** [comment]
Yes, better that way.
I didn't know the _missing_ method for enums. Cleaner than try/except :)

**Pull request closed without merging**
